services : 
  mysql:
    image : mysql:8.0
    container_name: mysql_logistik
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logistik_data
    ports:
      -"3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api : 
    build : 
      context: .
      dockerfile : dockerfile
    container_name: api_logistik
    depends_on:
    - mysql
    environment:
      - DB_HOST = mysql
      - DB_USER = root
      - DB_PASSWORD = root
      - DB_NAME = logistik_data
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data: